[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node -r ts-node/register src/db/migrate.ts && node -r ts-node/register src/index.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
